### ISSUE TITLE
How to use a local font

### ISSUE THREAD

**Issue by not-alaris** [PrettyCoffee/yet-another-generic-startpage#1]
Ok, so this is really stupid, but how can I choose to use a local font instead of one fetched from google fonts?

**Comment by PrettyCoffee** [comment]
You should be able by just putting the font name into the field.
For example if you have installed the font `ADELIA` locally on your machine and type it into the font input field, the startpage will set it as font even tho its not available on google fonts.

You can think of it like the startpage trying to get it from google fonts, if its not available there it will search on your machine, if not there it will use a default browser font instead.
