### ISSUE TITLE
how to set local gif

### ISSUE THREAD

**Issue by AT-Geist** [PrettyCoffee/yet-another-generic-startpage#25]
Hi, 
I want to use a custom gif on the start page. Is there a way to use a gif from my system?

**Comment by PrettyCoffee** [comment]
Hey :)
That's not possible due to security restrictions in browsers. However, you can upload it somewhere and use the link from there. For example on [imgur](https://imgur.com/).

**Comment by AT-Geist** [comment]
Got it,
thank you for the response! :D
