### ISSUE TITLE
Not an issue, but a request

### ISSUE THREAD

**Issue by Softboi1** [PrettyCoffee/yet-another-generic-startpage#28]
is it possible for you to make it so i can input my own custom search engine, instead of preset ones like google and duckduckgo?

**Comment by PrettyCoffee** [comment]
Added ✅

You can just copy the url of the search engine and put a `{query}` where the word should be inserted.

For example when searching for "hello world" on brave search, the url would be:
```
https://search.brave.com/search?q=hello+world
```

And then you can use this url in the settings text field:

![image](https://github.com/PrettyCoffee/yet-another-generic-startpage/assets/66521452/65887f15-ed3b-4e7c-b6ce-70aa5bc256ed)
