### ISSUE TITLE
Some questions and a little help

### ISSUE THREAD

**Issue by rd-626** [PrettyCoffee/yet-another-generic-startpage#29]
#### I loved the themes! Great job all of you guys, you have done grate!!!
I created a copy with `Mini Yags`, I noticed the gif image gets downloaded the first time you open index.html file.

- [ ] Where is the gif file stored? (I'm on linux)
- [ ] My favicon.ico file is empty, why? (doesn't even matter if I delete it so why is it there? bug perhaps?)

I haven't done any web development yet, also don't know JS

**Comment by PrettyCoffee** [comment]
Hi, thank you for the kind words! :)

> Where is the gif file stored? (I'm on linux)

In the internet ;)
It is not stored on your local system. Instead, you set a link to the image or gif in the settings and it is loaded from there each time you open the site.
If you want to use a local gif with mini yags, you can put it in your mini yags directory and change the following line in the `index.html`:
```
<img src="https://some-image-url..." alt="" />
```
to
```
<img src="./your-file.gif" alt="" />
```

> My favicon.ico file is empty, why?

I actually have no idea, looks like something broke there.
However, you can download it directly from the repo:
https://github.com/PrettyCoffee/yet-another-generic-startpage/blob/master/public/favicon.ico
and replace the file in your directory.
