### ISSUE TITLE
Is it possible to have the search bar both search google and open urls?

### ISSUE THREAD

**Issue by oaroki-git** [PrettyCoffee/yet-another-generic-startpage#30]
if not, it would be nice if there was an option to focus the url bar of the browser itself

**Comment by oaroki-git** [comment]
fixed, there was an option in the New Tab Redirect extension

**Comment by oaroki-git** [comment]
would still be cool if the bar in the page itself could do it both though

**Comment by PrettyCoffee** [comment]
Hey @oaroki-git, can you describe more in detail what you mean by that or give an example of the userflow? :)

**Comment by oaroki-git** [comment]
hello there, thank you for reaching out

here is what i was imagining:
if i type a url out, i would go to that url instead of the google search of
that website.

if i type anything else, it would be treated as a search engine search term

**Comment by PrettyCoffee** [comment]
That is actually already implemented. For example, if you paste this link:
```
https://github.com/PrettyCoffee/yet-another-generic-startpage
```
and then press Enter, it should be opened automatically.
