### ISSUE TITLE
can't find where to change bookmark links and category names in the offline mini-YAGS folder

### ISSUE THREAD

**Issue by oaroki-git** [PrettyCoffee/yet-another-generic-startpage#31]

**Comment by oaroki-git** [comment]
there seems to only be styling options

the closest i could find is a blank section in index.html

**Comment by PrettyCoffee** [comment]
Hey, check out the `scripts.js` file which is included in the files. There is a variable called `bookmarks`. There you can change the bookmarks and categories. (you can ignore the ids)
